"""
Labeled training data for intent classification.

Each intent has 50-100+ example utterances that a user might say.
Used by IntentClassifier to train a sentence-transformer + LogisticRegression model.
"""

INTENT_TRAINING_DATA = {
    "greeting": [
        "hello",
        "hi",
        "hey",
        "good morning",
        "good afternoon",
        "good evening",
        "hi there",
        "hey there",
        "howdy",
        "greetings",
        "what's up",
        "yo",
        "hiya",
        "sup",
        "hello there",
        "hey bot",
        "hi bot",
        "morning",
        "afternoon",
        "evening",
        "hello chatbot",
        "hi chatbot",
        "hey buddy",
        "good day",
        "hi, how are you",
        "hello, can you help me",
        "hey, I need help",
        "greetings friend",
        "hi, I'm new here",
        "hello, is anyone there",
    ],

    "goodbye": [
        "bye",
        "goodbye",
        "see you",
        "farewell",
        "see you later",
        "bye bye",
        "take care",
        "good night",
        "later",
        "I'm done",
        "that's all",
        "thanks bye",
        "thank you goodbye",
        "cheers",
        "catch you later",
        "I'm leaving",
        "gotta go",
        "have a good day",
        "have a nice day",
        "see ya",
        "talk to you later",
        "thanks, that's all I needed",
        "okay thanks bye",
        "alright see you",
        "peace out",
        "I'm off",
        "ttyl",
        "goodnight",
        "cya",
        "signing off",
    ],

    "ask_timetable": [
        "bus times for Oxford Circus",
        "train times at Wembley",
        "when is the next bus from Neasden",
        "timetable for Baker Street",
        "what time is the next train to Paddington",
        "tube times at Victoria",
        "next bus at Lavender Avenue",
        "bus and train times for Harrow",
        "what buses come to Oxford Circus",
        "when does the next 83 bus come",
        "bus 302 timetable",
        "show me the train schedule for Kings Cross",
        "what time do trains leave from Euston",
        "next train from Waterloo",
        "when is the next tube from Piccadilly Circus",
        "bus times near me",
        "train times for Finchley Road",
        "what time is the 83 bus",
        "give me the timetable for Wembley Central",
        "times for Neasden station",
        "next bus to Willesden",
        "next train at Liverpool Street",
        "show bus arrivals at Camden",
        "bus schedule for Brixton",
        "when is the next 18 bus at Wembley",
        "train arrivals at Stratford",
        "tube schedule for Northern line at Camden",
        "departures from Paddington station",
        "what buses stop at Lavender Avenue",
        "when is the next bus or train from Harlesden",
        "check times for Kilburn station",
        "bus or train times for Stonebridge Park",
        "what time does the next Northern line train leave",
        "give me arrivals for the 83 at Wembley",
        "show the timetable for Dollis Hill",
        "next departure from Neasden to Baker Street",
        "how long until the next bus at my stop",
        "bus arrival times",
        "train departure times",
        "when does the next DLR leave",
        "overground times at Willesden Junction",
        "next bus at the stop near me",
        "is there a bus coming soon to Kingsbury",
        "what time does the last train leave",
        "first bus in the morning from Wembley",
        "late night bus times",
        "night bus schedule for N83",
        "what time is the N18 bus",
        "check the arrivals board for this station",
        "live departures from Baker Street",
        "whats the bus times from harrow on the hill to south harrow",
        "what are the bus times from Harrow on the Hill to South Harrow",
        "bus times from Harrow on the Hill to South Harrow",
    ],

    "ask_transit_disruption": [
        "is the Northern line running",
        "any disruptions on the Bakerloo line",
        "is there a delay on the Central line",
        "tube status",
        "train line status",
        "are there any problems on the District line",
        "is the Jubilee line disrupted",
        "check disruptions on the Piccadilly line",
        "Metropolitan line status",
        "is the Victoria line working",
        "what's the status of the Circle line",
        "any issues on the Hammersmith line",
        "DLR service status",
        "overground disruptions",
        "is the bus route 83 running",
        "bus 302 disruptions",
        "are there delays on bus route 18",
        "status of bus 83",
        "any problems with the 83 bus",
        "is bus 73 delayed",
        "check if the Northern line is running normally",
        "are there closures on the Central line",
        "Waterloo and City line status",
        "Windrush line disruptions",
        "Lioness line status",
        "Mildmay line running",
        "is the Elizabeth line delayed",
        "tramlink status",
        "any service disruptions today",
        "which lines have delays",
        "get me the tube status for all lines",
        "show line status",
        "are trains running normally",
        "planned engineering works on the Northern line",
        "weekend closures",
        "is there a strike today",
        "signal failure on the Jubilee line",
        "suspension on the District line",
        "part closure on the Metropolitan line",
        "good service on all lines",
        "which tube lines are disrupted right now",
        "bus status for route 25",
        "are night tubes running",
        "is the last train affected by disruptions",
        "service update for the Piccadilly line",
        "any changes to the Northern line this weekend",
        "is there a replacement bus service",
        "rail replacement on the overground",
        "planned disruptions this week",
        "emergency closure on the Central line",
        # --- Soft-language / colloquial disruption queries ---
        "is the Northern line okay",
        "is the Northern line okay today",
        "is the Central line alright",
        "is the Jubilee line fine",
        "is the Bakerloo line fine today",
        "is the tube okay",
        "is the tube alright today",
        "is the District line doing okay",
        "is the Piccadilly line all good",
        "is the Metropolitan line running okay",
        "I wonder if the Northern line is okay today",
        "I wonder if the tube is fine",
        "I wonder if the Central line is alright",
        "is the Victoria line good to go",
        "is the Circle line running fine",
        "are the trains okay today",
        "are the buses running alright",
        "is everything okay on the Northern line",
        "is the Elizabeth line alright today",
        "any problems with the Northern line today",
        "how is the Northern line doing",
        "how is the Jubilee line today",
        "how are the trains running today",
        "is the Northern line behaving today",
        "is the Northern line working today",
        "how is the tube running",
        "is the DLR running fine today",
        "is the overground okay",
        "is the Hammersmith line running alright",
    ],

    "journey_planning": [
        "plan a journey from Neasden to Oxford Circus",
        "plan a trip from Wembley to Paddington",
        "plan my journey from Harlesden to Brixton",
        "help me plan a journey from Kilburn to Liverpool Street",
        "I need to go from Wembley Park to Bank, can you plan a journey",
        "what is the best route from Neasden to Waterloo",
        "what is the best way to get from Wembley to central London",
        "show me routes from Kilburn to Kings Cross",
        "how do I get from Willesden Junction to Oxford Circus",
        "fastest route from Stonebridge Park to Victoria",
        "what is the quickest way from Harrow to London Bridge",
        "find me a route from Wembley Stadium to Stratford",
        "journey from Paddington to Canary Wharf",
        "how can I travel from Baker Street to Greenwich",
        "route from Euston to Heathrow by public transport",
        "what is the easiest route from Neasden to Camden Town",
        "how do I get from Kensal Green to Shoreditch",
        "plan a journey from Kilburn High Road to Clapham Junction",
        "I want to go from Wembley Central to Oxford Circus",
        "I want to travel from Harlesden to Holborn, what route should I take",
        "I need directions from Queens Park to Tottenham Court Road",
        "show me a journey from West Hampstead to Westminster",
        "how should I get from Brent Cross to Piccadilly Circus",
        "plan a journey from Willesden Green to Old Street",
        "what is the best way to get from Neasden station to Gatwick Airport",
        "how do I get from South Hampstead to Canary Wharf by tube",
        "plan a journey from Wembley Park to London Bridge at 6pm",
        "I need a route from Barnet to Oxford Circus tomorrow morning",
        "best public transport route from Harrow-on-the-Hill to Bank",
        "how can I get from Kilburn to Soho late at night",
        "plan a journey from Wembley to Kingston upon Thames",
        "I need to go from Wembley to Croydon, what is the best route",
        "what is the best way to get from Watford Junction to Euston",
        "find a route from Neasden to Greenwich by tube and DLR",
        "plan a journey from Wembley to Canary Wharf using public transport",
        "I want to travel from Harrow to London Bridge at 8am",
        "how do I get from Wembley to Shoreditch High Street",
        "show me the best route from Neasden to Victoria Station",
        "plan a journey from Willesden Junction to Farringdon",
        "journey from Kilburn Park to Oxford Circus with fewest changes",
    ],
}

# All intent labels (derived from training data keys)
INTENT_LABELS = list(INTENT_TRAINING_DATA.keys())
